GRANT ALL PRIVILEGES ON *.* TO 'bender'@'localhost' IDENTIFIED BY PASSWORD '*23AE809DDACAF96AF0FD78ED04B6A265E05AA257' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `bender\_%`.* TO 'bender'@'localhost';
FLUSH PRIVILEGES;

