language: php

php:
  - 5.3
  - 5.4

before_script:
  - php composer.phar update
  - mysql -e 'create database IF NOT EXISTS bender;' -uroot
  - mysql -uroot bender < dev_dump.sql

script: phpunit --coverage-text Test/