language: php

php:
  - 5.3
  - 5.4

before_script:
  - php composer.phar --quiet install 
  - mysql -e 'create database IF NOT EXISTS bender;' -uroot
  - mysql -uroot bender < Test/config/fix_priviligies.sql
  - mysql -uroot bender < dev_dump.sql
  - php bender.php create zf

script: phpunit --coverage-text Test/
