schema:
  Person:
    tablename: bender_persons
  Post:
    tablename: bender_posts
    options: { crud: 1}
  User:
    tablename: bender_users
  Worker:
    tablename: bender_workers
    extends: Person