schema:
  Person:
    tablename: bender_persons
  Post:
    tablename: bender_posts
    options: 
      crud: true
  User:
    tablename: bender_users
  Worker:
    tablename: bender_workers
    extends: Person