schema:
  Person:
    tablename: bender_persons
    options:
      form: true
  Post:
    tablename: bender_posts
    options: 
      crud: true
  User:
    tablename: bender_users
    extends: Person
    options:
      crud: true
  Worker:
    tablename: bender_workers
    extends: Person
    options:
      crud: true