schema:
  AccessRole:
    tablename: pcs_common_access_roles
    options:
      crud: true
  Address:
    tablename: pcs_common_addresses
    options: 
      form: true
  Email:
    tablename: pcs_common_emails
    options: 
      form: true
  MenuItem:
    tablename: pcs_common_menu_items
  Person:
    tablename: pcs_common_persons
    options: 
      form: true
  PhoneNumber:
    tablename: pcs_common_phone_numbers
    options: 
      form: true
  SecurityAction:
    tablename: pcs_common_security_actions
  SecurityController:
    tablename: pcs_common_security_controllers
  UserLog:
    tablename: pcs_common_user_logs
  User:
    tablename: pcs_common_users
    extends: Person
    options: 
      crud: true
