settings:
  encoding:   UTF-8
  output_dir: output
  db:
    dbname:   bender
    user:     bender
    password: 123
    host:     localhost
    driver:   pdo_mysql 
  options:
    author:   chente
  ZF: 
    application_namespace: Application 
    zf_version: 1 
  alias:
    zf:
      project: ZF
      modules: [ Bean, Collection, Factory, Catalog, Exception, Query, Unit, Form, CRUD]       
    schema:
      project: Core
      modules: [ Schema ]