settings:
  encoding:   UTF-8
  output_dir: output
  db:
    dbname:   bender
    user:     bender
    password: 123
    host:     localhost
    driver:   pdo_mysql 
  options:
    meta:
      author:      chente
      company:     Bender
      copyright:   Copyright (c) 2012 Bender (https://github.com/chentepixtol/Bender2)
      description: Example Project created by Bender Code Generator
      version:     1.0 alpha 
  ZF: 
    application_namespace: Application 
    zf_version: 1
  alias:
    zf:
      project: ZF
      modules: [ Bean, Collection, Factory, Catalog, Exception, Query, Form, CRUD, Unit]       
    schema:
      project: Core
      modules: [ Schema ]