settings:
  encoding:   UTF-8
  output_dir: output
  db:
    dbname:   bender
    user:     bender
    password: 123
    host:     localhost
    driver:   pdo_mysql 
  options:
    author:   chente
    applicationNamespace: Application
  alias:
    zf2:
      project: ZF2
      modules: [ Bean, Collection, Factory, Catalog, Exception, Query, Unit, Form ]
    schema:
      project: Core
      modules: [ Schema ]