settings:
  encoding:   UTF-8
  output_dir: output
  db:
    dbname:   bender
    user:     bender
    password: 123
    host:     localhost
    driver:   pdo_mysql 
  options:
    author:   chente
  alias:
    all:
      project: MyProject
      modules: [ Bean, Collection, Factory, Catalog, Exception, Query, Unit ]
    schema:
      project: Core
      modules: [ Schema ]