<phpunit 
    bootstrap="Test/bootstrap.php"
    cacheTokens="true"
    colors="false"
    convertErrorsToExceptions="true"
    convertNoticesToExceptions="false"
    convertWarningsToExceptions="true"
    processIsolation="false"
    stopOnError="false"
    stopOnFailure="false"
    stopOnIncomplete="false"
    stopOnSkipped="false"
    strict="true"
    verbose="true">
</phpunit>
